# Generated DSF_MAPPING - Complete SYSCOHADA accounts to DSF mapping
# This maps all SYSCOHADA account numbers to their corresponding DSF cells

DSF_MAPPING = {
    # DSF Reference: AD
    "2011": BalanceLigneMapping(compte_syscohada="2011", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2012": BalanceLigneMapping(compte_syscohada="2012", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2013": BalanceLigneMapping(compte_syscohada="2013", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2014": BalanceLigneMapping(compte_syscohada="2014", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2015": BalanceLigneMapping(compte_syscohada="2015", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2016": BalanceLigneMapping(compte_syscohada="2016", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2017": BalanceLigneMapping(compte_syscohada="2017", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2018": BalanceLigneMapping(compte_syscohada="2018", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2021": BalanceLigneMapping(compte_syscohada="2021", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2022": BalanceLigneMapping(compte_syscohada="2022", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2026": BalanceLigneMapping(compte_syscohada="2026", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2028": BalanceLigneMapping(compte_syscohada="2028", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "206": BalanceLigneMapping(compte_syscohada="206", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2061": BalanceLigneMapping(compte_syscohada="2061", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2062": BalanceLigneMapping(compte_syscohada="2062", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2068": BalanceLigneMapping(compte_syscohada="2068", dsf_sheet="BILAN PAYSAGE", dsf_cell="AD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: AE
    "201": BalanceLigneMapping(compte_syscohada="201", dsf_sheet="BILAN PAYSAGE", dsf_cell="AE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: AF
    "202": BalanceLigneMapping(compte_syscohada="202", dsf_sheet="BILAN PAYSAGE", dsf_cell="AF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: AI
    "215": BalanceLigneMapping(compte_syscohada="215", dsf_sheet="BILAN PAYSAGE", dsf_cell="AI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "216": BalanceLigneMapping(compte_syscohada="216", dsf_sheet="BILAN PAYSAGE", dsf_cell="AI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "217": BalanceLigneMapping(compte_syscohada="217", dsf_sheet="BILAN PAYSAGE", dsf_cell="AI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "218": BalanceLigneMapping(compte_syscohada="218", dsf_sheet="BILAN PAYSAGE", dsf_cell="AI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "219": BalanceLigneMapping(compte_syscohada="219", dsf_sheet="BILAN PAYSAGE", dsf_cell="AI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2191": BalanceLigneMapping(compte_syscohada="2191", dsf_sheet="BILAN PAYSAGE", dsf_cell="AI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2193": BalanceLigneMapping(compte_syscohada="2193", dsf_sheet="BILAN PAYSAGE", dsf_cell="AI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2198": BalanceLigneMapping(compte_syscohada="2198", dsf_sheet="BILAN PAYSAGE", dsf_cell="AI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: AK
    "211": BalanceLigneMapping(compte_syscohada="211", dsf_sheet="BILAN PAYSAGE", dsf_cell="AK", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: AL
    "212": BalanceLigneMapping(compte_syscohada="212", dsf_sheet="BILAN PAYSAGE", dsf_cell="AL", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: AM
    "213": BalanceLigneMapping(compte_syscohada="213", dsf_sheet="BILAN PAYSAGE", dsf_cell="AM", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: AN
    "214": BalanceLigneMapping(compte_syscohada="214", dsf_sheet="BILAN PAYSAGE", dsf_cell="AN", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: AP
    "231": BalanceLigneMapping(compte_syscohada="231", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2311": BalanceLigneMapping(compte_syscohada="2311", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2312": BalanceLigneMapping(compte_syscohada="2312", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2313": BalanceLigneMapping(compte_syscohada="2313", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2314": BalanceLigneMapping(compte_syscohada="2314", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2315": BalanceLigneMapping(compte_syscohada="2315", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "232": BalanceLigneMapping(compte_syscohada="232", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2321": BalanceLigneMapping(compte_syscohada="2321", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2322": BalanceLigneMapping(compte_syscohada="2322", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2323": BalanceLigneMapping(compte_syscohada="2323", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2324": BalanceLigneMapping(compte_syscohada="2324", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2325": BalanceLigneMapping(compte_syscohada="2325", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "233": BalanceLigneMapping(compte_syscohada="233", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2331": BalanceLigneMapping(compte_syscohada="2331", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2332": BalanceLigneMapping(compte_syscohada="2332", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2333": BalanceLigneMapping(compte_syscohada="2333", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2334": BalanceLigneMapping(compte_syscohada="2334", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2335": BalanceLigneMapping(compte_syscohada="2335", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2338": BalanceLigneMapping(compte_syscohada="2338", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "234": BalanceLigneMapping(compte_syscohada="234", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2341": BalanceLigneMapping(compte_syscohada="2341", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2342": BalanceLigneMapping(compte_syscohada="2342", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2343": BalanceLigneMapping(compte_syscohada="2343", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2344": BalanceLigneMapping(compte_syscohada="2344", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "235": BalanceLigneMapping(compte_syscohada="235", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2351": BalanceLigneMapping(compte_syscohada="2351", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2358": BalanceLigneMapping(compte_syscohada="2358", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "237": BalanceLigneMapping(compte_syscohada="237", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "238": BalanceLigneMapping(compte_syscohada="238", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "239": BalanceLigneMapping(compte_syscohada="239", dsf_sheet="BILAN PAYSAGE", dsf_cell="AP", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: AQ
    "2411": BalanceLigneMapping(compte_syscohada="2411", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2412": BalanceLigneMapping(compte_syscohada="2412", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2413": BalanceLigneMapping(compte_syscohada="2413", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2414": BalanceLigneMapping(compte_syscohada="2414", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "242": BalanceLigneMapping(compte_syscohada="242", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2421": BalanceLigneMapping(compte_syscohada="2421", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2422": BalanceLigneMapping(compte_syscohada="2422", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "243": BalanceLigneMapping(compte_syscohada="243", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "244": BalanceLigneMapping(compte_syscohada="244", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2441": BalanceLigneMapping(compte_syscohada="2441", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2442": BalanceLigneMapping(compte_syscohada="2442", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2443": BalanceLigneMapping(compte_syscohada="2443", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2444": BalanceLigneMapping(compte_syscohada="2444", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2446": BalanceLigneMapping(compte_syscohada="2446", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2447": BalanceLigneMapping(compte_syscohada="2447", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "245": BalanceLigneMapping(compte_syscohada="245", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2451": BalanceLigneMapping(compte_syscohada="2451", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2452": BalanceLigneMapping(compte_syscohada="2452", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2453": BalanceLigneMapping(compte_syscohada="2453", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2454": BalanceLigneMapping(compte_syscohada="2454", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2455": BalanceLigneMapping(compte_syscohada="2455", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2456": BalanceLigneMapping(compte_syscohada="2456", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2458": BalanceLigneMapping(compte_syscohada="2458", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "246": BalanceLigneMapping(compte_syscohada="246", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2461": BalanceLigneMapping(compte_syscohada="2461", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2462": BalanceLigneMapping(compte_syscohada="2462", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2463": BalanceLigneMapping(compte_syscohada="2463", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2465": BalanceLigneMapping(compte_syscohada="2465", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2468": BalanceLigneMapping(compte_syscohada="2468", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "247": BalanceLigneMapping(compte_syscohada="247", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2481": BalanceLigneMapping(compte_syscohada="2481", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "249": BalanceLigneMapping(compte_syscohada="249", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2491": BalanceLigneMapping(compte_syscohada="2491", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2492": BalanceLigneMapping(compte_syscohada="2492", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2493": BalanceLigneMapping(compte_syscohada="2493", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2494": BalanceLigneMapping(compte_syscohada="2494", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2495": BalanceLigneMapping(compte_syscohada="2495", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2496": BalanceLigneMapping(compte_syscohada="2496", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2497": BalanceLigneMapping(compte_syscohada="2497", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "2498": BalanceLigneMapping(compte_syscohada="2498", dsf_sheet="BILAN PAYSAGE", dsf_cell="AQ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: AR
    "241": BalanceLigneMapping(compte_syscohada="241", dsf_sheet="BILAN PAYSAGE", dsf_cell="AR", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: AS
    "248": BalanceLigneMapping(compte_syscohada="248", dsf_sheet="BILAN PAYSAGE", dsf_cell="AS", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: BB
    "311": BalanceLigneMapping(compte_syscohada="311", dsf_sheet="BILAN PAYSAGE", dsf_cell="BB", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3111": BalanceLigneMapping(compte_syscohada="3111", dsf_sheet="BILAN PAYSAGE", dsf_cell="BB", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3112": BalanceLigneMapping(compte_syscohada="3112", dsf_sheet="BILAN PAYSAGE", dsf_cell="BB", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "312": BalanceLigneMapping(compte_syscohada="312", dsf_sheet="BILAN PAYSAGE", dsf_cell="BB", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3121": BalanceLigneMapping(compte_syscohada="3121", dsf_sheet="BILAN PAYSAGE", dsf_cell="BB", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3122": BalanceLigneMapping(compte_syscohada="3122", dsf_sheet="BILAN PAYSAGE", dsf_cell="BB", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "318": BalanceLigneMapping(compte_syscohada="318", dsf_sheet="BILAN PAYSAGE", dsf_cell="BB", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: BC
    "321": BalanceLigneMapping(compte_syscohada="321", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "322": BalanceLigneMapping(compte_syscohada="322", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "323": BalanceLigneMapping(compte_syscohada="323", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "501": BalanceLigneMapping(compte_syscohada="501", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5011": BalanceLigneMapping(compte_syscohada="5011", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5012": BalanceLigneMapping(compte_syscohada="5012", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5013": BalanceLigneMapping(compte_syscohada="5013", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "502": BalanceLigneMapping(compte_syscohada="502", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5021": BalanceLigneMapping(compte_syscohada="5021", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5022": BalanceLigneMapping(compte_syscohada="5022", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5023": BalanceLigneMapping(compte_syscohada="5023", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5024": BalanceLigneMapping(compte_syscohada="5024", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5025": BalanceLigneMapping(compte_syscohada="5025", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "503": BalanceLigneMapping(compte_syscohada="503", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5031": BalanceLigneMapping(compte_syscohada="5031", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5032": BalanceLigneMapping(compte_syscohada="5032", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5033": BalanceLigneMapping(compte_syscohada="5033", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5035": BalanceLigneMapping(compte_syscohada="5035", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "504": BalanceLigneMapping(compte_syscohada="504", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5042": BalanceLigneMapping(compte_syscohada="5042", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5043": BalanceLigneMapping(compte_syscohada="5043", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "505": BalanceLigneMapping(compte_syscohada="505", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "506": BalanceLigneMapping(compte_syscohada="506", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5061": BalanceLigneMapping(compte_syscohada="5061", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5062": BalanceLigneMapping(compte_syscohada="5062", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "5063": BalanceLigneMapping(compte_syscohada="5063", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "508": BalanceLigneMapping(compte_syscohada="508", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "512": BalanceLigneMapping(compte_syscohada="512", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "521": BalanceLigneMapping(compte_syscohada="521", dsf_sheet="BILAN PAYSAGE", dsf_cell="BC", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: BD
    "331": BalanceLigneMapping(compte_syscohada="331", dsf_sheet="BILAN PAYSAGE", dsf_cell="BD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "332": BalanceLigneMapping(compte_syscohada="332", dsf_sheet="BILAN PAYSAGE", dsf_cell="BD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "333": BalanceLigneMapping(compte_syscohada="333", dsf_sheet="BILAN PAYSAGE", dsf_cell="BD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "334": BalanceLigneMapping(compte_syscohada="334", dsf_sheet="BILAN PAYSAGE", dsf_cell="BD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "335": BalanceLigneMapping(compte_syscohada="335", dsf_sheet="BILAN PAYSAGE", dsf_cell="BD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3351": BalanceLigneMapping(compte_syscohada="3351", dsf_sheet="BILAN PAYSAGE", dsf_cell="BD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3352": BalanceLigneMapping(compte_syscohada="3352", dsf_sheet="BILAN PAYSAGE", dsf_cell="BD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3353": BalanceLigneMapping(compte_syscohada="3353", dsf_sheet="BILAN PAYSAGE", dsf_cell="BD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3358": BalanceLigneMapping(compte_syscohada="3358", dsf_sheet="BILAN PAYSAGE", dsf_cell="BD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "338": BalanceLigneMapping(compte_syscohada="338", dsf_sheet="BILAN PAYSAGE", dsf_cell="BD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: BE
    "341": BalanceLigneMapping(compte_syscohada="341", dsf_sheet="BILAN PAYSAGE", dsf_cell="BE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3411": BalanceLigneMapping(compte_syscohada="3411", dsf_sheet="BILAN PAYSAGE", dsf_cell="BE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3412": BalanceLigneMapping(compte_syscohada="3412", dsf_sheet="BILAN PAYSAGE", dsf_cell="BE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "342": BalanceLigneMapping(compte_syscohada="342", dsf_sheet="BILAN PAYSAGE", dsf_cell="BE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3421": BalanceLigneMapping(compte_syscohada="3421", dsf_sheet="BILAN PAYSAGE", dsf_cell="BE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3422": BalanceLigneMapping(compte_syscohada="3422", dsf_sheet="BILAN PAYSAGE", dsf_cell="BE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "343": BalanceLigneMapping(compte_syscohada="343", dsf_sheet="BILAN PAYSAGE", dsf_cell="BE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3431": BalanceLigneMapping(compte_syscohada="3431", dsf_sheet="BILAN PAYSAGE", dsf_cell="BE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3432": BalanceLigneMapping(compte_syscohada="3432", dsf_sheet="BILAN PAYSAGE", dsf_cell="BE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "344": BalanceLigneMapping(compte_syscohada="344", dsf_sheet="BILAN PAYSAGE", dsf_cell="BE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3441": BalanceLigneMapping(compte_syscohada="3441", dsf_sheet="BILAN PAYSAGE", dsf_cell="BE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3442": BalanceLigneMapping(compte_syscohada="3442", dsf_sheet="BILAN PAYSAGE", dsf_cell="BE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: BF
    "351": BalanceLigneMapping(compte_syscohada="351", dsf_sheet="BILAN PAYSAGE", dsf_cell="BF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3511": BalanceLigneMapping(compte_syscohada="3511", dsf_sheet="BILAN PAYSAGE", dsf_cell="BF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3512": BalanceLigneMapping(compte_syscohada="3512", dsf_sheet="BILAN PAYSAGE", dsf_cell="BF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "352": BalanceLigneMapping(compte_syscohada="352", dsf_sheet="BILAN PAYSAGE", dsf_cell="BF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3521": BalanceLigneMapping(compte_syscohada="3521", dsf_sheet="BILAN PAYSAGE", dsf_cell="BF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "3522": BalanceLigneMapping(compte_syscohada="3522", dsf_sheet="BILAN PAYSAGE", dsf_cell="BF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: CA
    "101": BalanceLigneMapping(compte_syscohada="101", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1011": BalanceLigneMapping(compte_syscohada="1011", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1012": BalanceLigneMapping(compte_syscohada="1012", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1013": BalanceLigneMapping(compte_syscohada="1013", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1014": BalanceLigneMapping(compte_syscohada="1014", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1018": BalanceLigneMapping(compte_syscohada="1018", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1021": BalanceLigneMapping(compte_syscohada="1021", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1022": BalanceLigneMapping(compte_syscohada="1022", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1028": BalanceLigneMapping(compte_syscohada="1028", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "103": BalanceLigneMapping(compte_syscohada="103", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1041": BalanceLigneMapping(compte_syscohada="1041", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1042": BalanceLigneMapping(compte_syscohada="1042", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1043": BalanceLigneMapping(compte_syscohada="1043", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1047": BalanceLigneMapping(compte_syscohada="1047", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1048": BalanceLigneMapping(compte_syscohada="1048", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1051": BalanceLigneMapping(compte_syscohada="1051", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1052": BalanceLigneMapping(compte_syscohada="1052", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1053": BalanceLigneMapping(compte_syscohada="1053", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1054": BalanceLigneMapping(compte_syscohada="1054", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1058": BalanceLigneMapping(compte_syscohada="1058", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "106": BalanceLigneMapping(compte_syscohada="106", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1061": BalanceLigneMapping(compte_syscohada="1061", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1062": BalanceLigneMapping(compte_syscohada="1062", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "109": BalanceLigneMapping(compte_syscohada="109", dsf_sheet="BILAN PAYSAGE", dsf_cell="CA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: CB
    "102": BalanceLigneMapping(compte_syscohada="102", dsf_sheet="BILAN PAYSAGE", dsf_cell="CB", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: CD
    "104": BalanceLigneMapping(compte_syscohada="104", dsf_sheet="BILAN PAYSAGE", dsf_cell="CD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: CE
    "105": BalanceLigneMapping(compte_syscohada="105", dsf_sheet="BILAN PAYSAGE", dsf_cell="CE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: CF
    "111": BalanceLigneMapping(compte_syscohada="111", dsf_sheet="BILAN PAYSAGE", dsf_cell="CF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "112": BalanceLigneMapping(compte_syscohada="112", dsf_sheet="BILAN PAYSAGE", dsf_cell="CF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "113": BalanceLigneMapping(compte_syscohada="113", dsf_sheet="BILAN PAYSAGE", dsf_cell="CF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1131": BalanceLigneMapping(compte_syscohada="1131", dsf_sheet="BILAN PAYSAGE", dsf_cell="CF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1133": BalanceLigneMapping(compte_syscohada="1133", dsf_sheet="BILAN PAYSAGE", dsf_cell="CF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1138": BalanceLigneMapping(compte_syscohada="1138", dsf_sheet="BILAN PAYSAGE", dsf_cell="CF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "118": BalanceLigneMapping(compte_syscohada="118", dsf_sheet="BILAN PAYSAGE", dsf_cell="CF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1181": BalanceLigneMapping(compte_syscohada="1181", dsf_sheet="BILAN PAYSAGE", dsf_cell="CF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1188": BalanceLigneMapping(compte_syscohada="1188", dsf_sheet="BILAN PAYSAGE", dsf_cell="CF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: CG
    "121": BalanceLigneMapping(compte_syscohada="121", dsf_sheet="BILAN PAYSAGE", dsf_cell="CG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "129": BalanceLigneMapping(compte_syscohada="129", dsf_sheet="BILAN PAYSAGE", dsf_cell="CG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1291": BalanceLigneMapping(compte_syscohada="1291", dsf_sheet="BILAN PAYSAGE", dsf_cell="CG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1292": BalanceLigneMapping(compte_syscohada="1292", dsf_sheet="BILAN PAYSAGE", dsf_cell="CG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: CH
    "130": BalanceLigneMapping(compte_syscohada="130", dsf_sheet="BILAN PAYSAGE", dsf_cell="CH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1301": BalanceLigneMapping(compte_syscohada="1301", dsf_sheet="BILAN PAYSAGE", dsf_cell="CH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1309": BalanceLigneMapping(compte_syscohada="1309", dsf_sheet="BILAN PAYSAGE", dsf_cell="CH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "131": BalanceLigneMapping(compte_syscohada="131", dsf_sheet="BILAN PAYSAGE", dsf_cell="CH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "132": BalanceLigneMapping(compte_syscohada="132", dsf_sheet="BILAN PAYSAGE", dsf_cell="CH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1321": BalanceLigneMapping(compte_syscohada="1321", dsf_sheet="BILAN PAYSAGE", dsf_cell="CH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1322": BalanceLigneMapping(compte_syscohada="1322", dsf_sheet="BILAN PAYSAGE", dsf_cell="CH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "133": BalanceLigneMapping(compte_syscohada="133", dsf_sheet="BILAN PAYSAGE", dsf_cell="CH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "134": BalanceLigneMapping(compte_syscohada="134", dsf_sheet="BILAN PAYSAGE", dsf_cell="CH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "135": BalanceLigneMapping(compte_syscohada="135", dsf_sheet="BILAN PAYSAGE", dsf_cell="CH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "136": BalanceLigneMapping(compte_syscohada="136", dsf_sheet="BILAN PAYSAGE", dsf_cell="CH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "137": BalanceLigneMapping(compte_syscohada="137", dsf_sheet="BILAN PAYSAGE", dsf_cell="CH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "138": BalanceLigneMapping(compte_syscohada="138", dsf_sheet="BILAN PAYSAGE", dsf_cell="CH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "139": BalanceLigneMapping(compte_syscohada="139", dsf_sheet="BILAN PAYSAGE", dsf_cell="CH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: CJ
    "141": BalanceLigneMapping(compte_syscohada="141", dsf_sheet="BILAN PAYSAGE", dsf_cell="CJ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1411": BalanceLigneMapping(compte_syscohada="1411", dsf_sheet="BILAN PAYSAGE", dsf_cell="CJ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1412": BalanceLigneMapping(compte_syscohada="1412", dsf_sheet="BILAN PAYSAGE", dsf_cell="CJ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1413": BalanceLigneMapping(compte_syscohada="1413", dsf_sheet="BILAN PAYSAGE", dsf_cell="CJ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1414": BalanceLigneMapping(compte_syscohada="1414", dsf_sheet="BILAN PAYSAGE", dsf_cell="CJ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1415": BalanceLigneMapping(compte_syscohada="1415", dsf_sheet="BILAN PAYSAGE", dsf_cell="CJ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1416": BalanceLigneMapping(compte_syscohada="1416", dsf_sheet="BILAN PAYSAGE", dsf_cell="CJ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1417": BalanceLigneMapping(compte_syscohada="1417", dsf_sheet="BILAN PAYSAGE", dsf_cell="CJ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1418": BalanceLigneMapping(compte_syscohada="1418", dsf_sheet="BILAN PAYSAGE", dsf_cell="CJ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "142": BalanceLigneMapping(compte_syscohada="142", dsf_sheet="BILAN PAYSAGE", dsf_cell="CJ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "148": BalanceLigneMapping(compte_syscohada="148", dsf_sheet="BILAN PAYSAGE", dsf_cell="CJ", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: CL
    "151": BalanceLigneMapping(compte_syscohada="151", dsf_sheet="BILAN PAYSAGE", dsf_cell="CL", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "152": BalanceLigneMapping(compte_syscohada="152", dsf_sheet="BILAN PAYSAGE", dsf_cell="CL", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "153": BalanceLigneMapping(compte_syscohada="153", dsf_sheet="BILAN PAYSAGE", dsf_cell="CL", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1531": BalanceLigneMapping(compte_syscohada="1531", dsf_sheet="BILAN PAYSAGE", dsf_cell="CL", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1532": BalanceLigneMapping(compte_syscohada="1532", dsf_sheet="BILAN PAYSAGE", dsf_cell="CL", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "154": BalanceLigneMapping(compte_syscohada="154", dsf_sheet="BILAN PAYSAGE", dsf_cell="CL", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "155": BalanceLigneMapping(compte_syscohada="155", dsf_sheet="BILAN PAYSAGE", dsf_cell="CL", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1551": BalanceLigneMapping(compte_syscohada="1551", dsf_sheet="BILAN PAYSAGE", dsf_cell="CL", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "156": BalanceLigneMapping(compte_syscohada="156", dsf_sheet="BILAN PAYSAGE", dsf_cell="CL", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1561": BalanceLigneMapping(compte_syscohada="1561", dsf_sheet="BILAN PAYSAGE", dsf_cell="CL", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1562": BalanceLigneMapping(compte_syscohada="1562", dsf_sheet="BILAN PAYSAGE", dsf_cell="CL", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "157": BalanceLigneMapping(compte_syscohada="157", dsf_sheet="BILAN PAYSAGE", dsf_cell="CL", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "158": BalanceLigneMapping(compte_syscohada="158", dsf_sheet="BILAN PAYSAGE", dsf_cell="CL", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: DA
    "161": BalanceLigneMapping(compte_syscohada="161", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1611": BalanceLigneMapping(compte_syscohada="1611", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1612": BalanceLigneMapping(compte_syscohada="1612", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1618": BalanceLigneMapping(compte_syscohada="1618", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "162": BalanceLigneMapping(compte_syscohada="162", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "163": BalanceLigneMapping(compte_syscohada="163", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "165": BalanceLigneMapping(compte_syscohada="165", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1651": BalanceLigneMapping(compte_syscohada="1651", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1652": BalanceLigneMapping(compte_syscohada="1652", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "166": BalanceLigneMapping(compte_syscohada="166", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1661": BalanceLigneMapping(compte_syscohada="1661", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1662": BalanceLigneMapping(compte_syscohada="1662", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1663": BalanceLigneMapping(compte_syscohada="1663", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1664": BalanceLigneMapping(compte_syscohada="1664", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1665": BalanceLigneMapping(compte_syscohada="1665", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1667": BalanceLigneMapping(compte_syscohada="1667", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1668": BalanceLigneMapping(compte_syscohada="1668", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "167": BalanceLigneMapping(compte_syscohada="167", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1671": BalanceLigneMapping(compte_syscohada="1671", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1672": BalanceLigneMapping(compte_syscohada="1672", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1673": BalanceLigneMapping(compte_syscohada="1673", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1674": BalanceLigneMapping(compte_syscohada="1674", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1676": BalanceLigneMapping(compte_syscohada="1676", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "168": BalanceLigneMapping(compte_syscohada="168", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1681": BalanceLigneMapping(compte_syscohada="1681", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1682": BalanceLigneMapping(compte_syscohada="1682", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1683": BalanceLigneMapping(compte_syscohada="1683", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1684": BalanceLigneMapping(compte_syscohada="1684", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1685": BalanceLigneMapping(compte_syscohada="1685", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1686": BalanceLigneMapping(compte_syscohada="1686", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "401": BalanceLigneMapping(compte_syscohada="401", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4011": BalanceLigneMapping(compte_syscohada="4011", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4012": BalanceLigneMapping(compte_syscohada="4012", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4013": BalanceLigneMapping(compte_syscohada="4013", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4017": BalanceLigneMapping(compte_syscohada="4017", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "402": BalanceLigneMapping(compte_syscohada="402", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4021": BalanceLigneMapping(compte_syscohada="4021", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4022": BalanceLigneMapping(compte_syscohada="4022", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4023": BalanceLigneMapping(compte_syscohada="4023", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "408": BalanceLigneMapping(compte_syscohada="408", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4081": BalanceLigneMapping(compte_syscohada="4081", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4082": BalanceLigneMapping(compte_syscohada="4082", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4083": BalanceLigneMapping(compte_syscohada="4083", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4086": BalanceLigneMapping(compte_syscohada="4086", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "409": BalanceLigneMapping(compte_syscohada="409", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4091": BalanceLigneMapping(compte_syscohada="4091", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4092": BalanceLigneMapping(compte_syscohada="4092", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4093": BalanceLigneMapping(compte_syscohada="4093", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4094": BalanceLigneMapping(compte_syscohada="4094", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "4098": BalanceLigneMapping(compte_syscohada="4098", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "411": BalanceLigneMapping(compte_syscohada="411", dsf_sheet="BILAN PAYSAGE", dsf_cell="DA", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: DB
    "164": BalanceLigneMapping(compte_syscohada="164", dsf_sheet="BILAN PAYSAGE", dsf_cell="DB", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: DD
    "191": BalanceLigneMapping(compte_syscohada="191", dsf_sheet="BILAN PAYSAGE", dsf_cell="DD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "192": BalanceLigneMapping(compte_syscohada="192", dsf_sheet="BILAN PAYSAGE", dsf_cell="DD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "193": BalanceLigneMapping(compte_syscohada="193", dsf_sheet="BILAN PAYSAGE", dsf_cell="DD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "194": BalanceLigneMapping(compte_syscohada="194", dsf_sheet="BILAN PAYSAGE", dsf_cell="DD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "195": BalanceLigneMapping(compte_syscohada="195", dsf_sheet="BILAN PAYSAGE", dsf_cell="DD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "196": BalanceLigneMapping(compte_syscohada="196", dsf_sheet="BILAN PAYSAGE", dsf_cell="DD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "197": BalanceLigneMapping(compte_syscohada="197", dsf_sheet="BILAN PAYSAGE", dsf_cell="DD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1971": BalanceLigneMapping(compte_syscohada="1971", dsf_sheet="BILAN PAYSAGE", dsf_cell="DD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "198": BalanceLigneMapping(compte_syscohada="198", dsf_sheet="BILAN PAYSAGE", dsf_cell="DD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1981": BalanceLigneMapping(compte_syscohada="1981", dsf_sheet="BILAN PAYSAGE", dsf_cell="DD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1982": BalanceLigneMapping(compte_syscohada="1982", dsf_sheet="BILAN PAYSAGE", dsf_cell="DD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1983": BalanceLigneMapping(compte_syscohada="1983", dsf_sheet="BILAN PAYSAGE", dsf_cell="DD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "1988": BalanceLigneMapping(compte_syscohada="1988", dsf_sheet="BILAN PAYSAGE", dsf_cell="DD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: ED
    "601": BalanceLigneMapping(compte_syscohada="601", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6011": BalanceLigneMapping(compte_syscohada="6011", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6012": BalanceLigneMapping(compte_syscohada="6012", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6013": BalanceLigneMapping(compte_syscohada="6013", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6014": BalanceLigneMapping(compte_syscohada="6014", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6019": BalanceLigneMapping(compte_syscohada="6019", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "602": BalanceLigneMapping(compte_syscohada="602", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6021": BalanceLigneMapping(compte_syscohada="6021", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6022": BalanceLigneMapping(compte_syscohada="6022", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6023": BalanceLigneMapping(compte_syscohada="6023", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6024": BalanceLigneMapping(compte_syscohada="6024", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6029": BalanceLigneMapping(compte_syscohada="6029", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "603": BalanceLigneMapping(compte_syscohada="603", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6031": BalanceLigneMapping(compte_syscohada="6031", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6032": BalanceLigneMapping(compte_syscohada="6032", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6033": BalanceLigneMapping(compte_syscohada="6033", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "604": BalanceLigneMapping(compte_syscohada="604", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6041": BalanceLigneMapping(compte_syscohada="6041", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6042": BalanceLigneMapping(compte_syscohada="6042", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6043": BalanceLigneMapping(compte_syscohada="6043", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6044": BalanceLigneMapping(compte_syscohada="6044", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6046": BalanceLigneMapping(compte_syscohada="6046", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6047": BalanceLigneMapping(compte_syscohada="6047", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6049": BalanceLigneMapping(compte_syscohada="6049", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "605": BalanceLigneMapping(compte_syscohada="605", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6051": BalanceLigneMapping(compte_syscohada="6051", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6052": BalanceLigneMapping(compte_syscohada="6052", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6053": BalanceLigneMapping(compte_syscohada="6053", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6054": BalanceLigneMapping(compte_syscohada="6054", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6055": BalanceLigneMapping(compte_syscohada="6055", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6056": BalanceLigneMapping(compte_syscohada="6056", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6057": BalanceLigneMapping(compte_syscohada="6057", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6058": BalanceLigneMapping(compte_syscohada="6058", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6059": BalanceLigneMapping(compte_syscohada="6059", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "608": BalanceLigneMapping(compte_syscohada="608", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6081": BalanceLigneMapping(compte_syscohada="6081", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6082": BalanceLigneMapping(compte_syscohada="6082", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6083": BalanceLigneMapping(compte_syscohada="6083", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6089": BalanceLigneMapping(compte_syscohada="6089", dsf_sheet="BILAN PAYSAGE", dsf_cell="ED", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: EE
    "611": BalanceLigneMapping(compte_syscohada="611", dsf_sheet="BILAN PAYSAGE", dsf_cell="EE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "612": BalanceLigneMapping(compte_syscohada="612", dsf_sheet="BILAN PAYSAGE", dsf_cell="EE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "613": BalanceLigneMapping(compte_syscohada="613", dsf_sheet="BILAN PAYSAGE", dsf_cell="EE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "614": BalanceLigneMapping(compte_syscohada="614", dsf_sheet="BILAN PAYSAGE", dsf_cell="EE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "616": BalanceLigneMapping(compte_syscohada="616", dsf_sheet="BILAN PAYSAGE", dsf_cell="EE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "618": BalanceLigneMapping(compte_syscohada="618", dsf_sheet="BILAN PAYSAGE", dsf_cell="EE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6181": BalanceLigneMapping(compte_syscohada="6181", dsf_sheet="BILAN PAYSAGE", dsf_cell="EE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6182": BalanceLigneMapping(compte_syscohada="6182", dsf_sheet="BILAN PAYSAGE", dsf_cell="EE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6183": BalanceLigneMapping(compte_syscohada="6183", dsf_sheet="BILAN PAYSAGE", dsf_cell="EE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: EF
    "621": BalanceLigneMapping(compte_syscohada="621", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "622": BalanceLigneMapping(compte_syscohada="622", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6221": BalanceLigneMapping(compte_syscohada="6221", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6222": BalanceLigneMapping(compte_syscohada="6222", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6223": BalanceLigneMapping(compte_syscohada="6223", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6224": BalanceLigneMapping(compte_syscohada="6224", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6225": BalanceLigneMapping(compte_syscohada="6225", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6228": BalanceLigneMapping(compte_syscohada="6228", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "623": BalanceLigneMapping(compte_syscohada="623", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6232": BalanceLigneMapping(compte_syscohada="6232", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6233": BalanceLigneMapping(compte_syscohada="6233", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6235": BalanceLigneMapping(compte_syscohada="6235", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "624": BalanceLigneMapping(compte_syscohada="624", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6241": BalanceLigneMapping(compte_syscohada="6241", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6242": BalanceLigneMapping(compte_syscohada="6242", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6243": BalanceLigneMapping(compte_syscohada="6243", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6248": BalanceLigneMapping(compte_syscohada="6248", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "625": BalanceLigneMapping(compte_syscohada="625", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6251": BalanceLigneMapping(compte_syscohada="6251", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6252": BalanceLigneMapping(compte_syscohada="6252", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6253": BalanceLigneMapping(compte_syscohada="6253", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6254": BalanceLigneMapping(compte_syscohada="6254", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6255": BalanceLigneMapping(compte_syscohada="6255", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6256": BalanceLigneMapping(compte_syscohada="6256", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6257": BalanceLigneMapping(compte_syscohada="6257", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6258": BalanceLigneMapping(compte_syscohada="6258", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "626": BalanceLigneMapping(compte_syscohada="626", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6261": BalanceLigneMapping(compte_syscohada="6261", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6265": BalanceLigneMapping(compte_syscohada="6265", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6266": BalanceLigneMapping(compte_syscohada="6266", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "627": BalanceLigneMapping(compte_syscohada="627", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6271": BalanceLigneMapping(compte_syscohada="6271", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6272": BalanceLigneMapping(compte_syscohada="6272", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6273": BalanceLigneMapping(compte_syscohada="6273", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6274": BalanceLigneMapping(compte_syscohada="6274", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6275": BalanceLigneMapping(compte_syscohada="6275", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6276": BalanceLigneMapping(compte_syscohada="6276", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6277": BalanceLigneMapping(compte_syscohada="6277", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6278": BalanceLigneMapping(compte_syscohada="6278", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "628": BalanceLigneMapping(compte_syscohada="628", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6281": BalanceLigneMapping(compte_syscohada="6281", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6282": BalanceLigneMapping(compte_syscohada="6282", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6283": BalanceLigneMapping(compte_syscohada="6283", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6288": BalanceLigneMapping(compte_syscohada="6288", dsf_sheet="BILAN PAYSAGE", dsf_cell="EF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: EG
    "631": BalanceLigneMapping(compte_syscohada="631", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6311": BalanceLigneMapping(compte_syscohada="6311", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6312": BalanceLigneMapping(compte_syscohada="6312", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6313": BalanceLigneMapping(compte_syscohada="6313", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6315": BalanceLigneMapping(compte_syscohada="6315", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6316": BalanceLigneMapping(compte_syscohada="6316", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6318": BalanceLigneMapping(compte_syscohada="6318", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "632": BalanceLigneMapping(compte_syscohada="632", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6321": BalanceLigneMapping(compte_syscohada="6321", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6322": BalanceLigneMapping(compte_syscohada="6322", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6323": BalanceLigneMapping(compte_syscohada="6323", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6324": BalanceLigneMapping(compte_syscohada="6324", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6325": BalanceLigneMapping(compte_syscohada="6325", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6328": BalanceLigneMapping(compte_syscohada="6328", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "633": BalanceLigneMapping(compte_syscohada="633", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "634": BalanceLigneMapping(compte_syscohada="634", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6342": BalanceLigneMapping(compte_syscohada="6342", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6343": BalanceLigneMapping(compte_syscohada="6343", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6344": BalanceLigneMapping(compte_syscohada="6344", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "635": BalanceLigneMapping(compte_syscohada="635", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6351": BalanceLigneMapping(compte_syscohada="6351", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6358": BalanceLigneMapping(compte_syscohada="6358", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "637": BalanceLigneMapping(compte_syscohada="637", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6371": BalanceLigneMapping(compte_syscohada="6371", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6372": BalanceLigneMapping(compte_syscohada="6372", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "638": BalanceLigneMapping(compte_syscohada="638", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6381": BalanceLigneMapping(compte_syscohada="6381", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6382": BalanceLigneMapping(compte_syscohada="6382", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6383": BalanceLigneMapping(compte_syscohada="6383", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6384": BalanceLigneMapping(compte_syscohada="6384", dsf_sheet="BILAN PAYSAGE", dsf_cell="EG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: EH
    "641": BalanceLigneMapping(compte_syscohada="641", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6411": BalanceLigneMapping(compte_syscohada="6411", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6412": BalanceLigneMapping(compte_syscohada="6412", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6413": BalanceLigneMapping(compte_syscohada="6413", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6414": BalanceLigneMapping(compte_syscohada="6414", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6415": BalanceLigneMapping(compte_syscohada="6415", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6418": BalanceLigneMapping(compte_syscohada="6418", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "645": BalanceLigneMapping(compte_syscohada="645", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "646": BalanceLigneMapping(compte_syscohada="646", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6461": BalanceLigneMapping(compte_syscohada="6461", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6462": BalanceLigneMapping(compte_syscohada="6462", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6463": BalanceLigneMapping(compte_syscohada="6463", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6464": BalanceLigneMapping(compte_syscohada="6464", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6468": BalanceLigneMapping(compte_syscohada="6468", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "647": BalanceLigneMapping(compte_syscohada="647", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6471": BalanceLigneMapping(compte_syscohada="6471", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6472": BalanceLigneMapping(compte_syscohada="6472", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6473": BalanceLigneMapping(compte_syscohada="6473", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6474": BalanceLigneMapping(compte_syscohada="6474", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6478": BalanceLigneMapping(compte_syscohada="6478", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "648": BalanceLigneMapping(compte_syscohada="648", dsf_sheet="BILAN PAYSAGE", dsf_cell="EH", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: EI
    "651": BalanceLigneMapping(compte_syscohada="651", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6511": BalanceLigneMapping(compte_syscohada="6511", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6515": BalanceLigneMapping(compte_syscohada="6515", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "652": BalanceLigneMapping(compte_syscohada="652", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6521": BalanceLigneMapping(compte_syscohada="6521", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6525": BalanceLigneMapping(compte_syscohada="6525", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "653": BalanceLigneMapping(compte_syscohada="653", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "654": BalanceLigneMapping(compte_syscohada="654", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "658": BalanceLigneMapping(compte_syscohada="658", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6581": BalanceLigneMapping(compte_syscohada="6581", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6582": BalanceLigneMapping(compte_syscohada="6582", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6583": BalanceLigneMapping(compte_syscohada="6583", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "659": BalanceLigneMapping(compte_syscohada="659", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6591": BalanceLigneMapping(compte_syscohada="6591", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6593": BalanceLigneMapping(compte_syscohada="6593", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6594": BalanceLigneMapping(compte_syscohada="6594", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "6598": BalanceLigneMapping(compte_syscohada="6598", dsf_sheet="BILAN PAYSAGE", dsf_cell="EI", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: RD
    "701": BalanceLigneMapping(compte_syscohada="701", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7011": BalanceLigneMapping(compte_syscohada="7011", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7012": BalanceLigneMapping(compte_syscohada="7012", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7013": BalanceLigneMapping(compte_syscohada="7013", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7014": BalanceLigneMapping(compte_syscohada="7014", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "702": BalanceLigneMapping(compte_syscohada="702", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7021": BalanceLigneMapping(compte_syscohada="7021", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7022": BalanceLigneMapping(compte_syscohada="7022", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7023": BalanceLigneMapping(compte_syscohada="7023", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7024": BalanceLigneMapping(compte_syscohada="7024", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "703": BalanceLigneMapping(compte_syscohada="703", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7031": BalanceLigneMapping(compte_syscohada="7031", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7032": BalanceLigneMapping(compte_syscohada="7032", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7033": BalanceLigneMapping(compte_syscohada="7033", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7034": BalanceLigneMapping(compte_syscohada="7034", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "704": BalanceLigneMapping(compte_syscohada="704", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7041": BalanceLigneMapping(compte_syscohada="7041", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7042": BalanceLigneMapping(compte_syscohada="7042", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7043": BalanceLigneMapping(compte_syscohada="7043", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7044": BalanceLigneMapping(compte_syscohada="7044", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "705": BalanceLigneMapping(compte_syscohada="705", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7051": BalanceLigneMapping(compte_syscohada="7051", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7052": BalanceLigneMapping(compte_syscohada="7052", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7053": BalanceLigneMapping(compte_syscohada="7053", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7054": BalanceLigneMapping(compte_syscohada="7054", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "706": BalanceLigneMapping(compte_syscohada="706", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7061": BalanceLigneMapping(compte_syscohada="7061", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7062": BalanceLigneMapping(compte_syscohada="7062", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7063": BalanceLigneMapping(compte_syscohada="7063", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7064": BalanceLigneMapping(compte_syscohada="7064", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "707": BalanceLigneMapping(compte_syscohada="707", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7071": BalanceLigneMapping(compte_syscohada="7071", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7072": BalanceLigneMapping(compte_syscohada="7072", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7073": BalanceLigneMapping(compte_syscohada="7073", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7074": BalanceLigneMapping(compte_syscohada="7074", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7075": BalanceLigneMapping(compte_syscohada="7075", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7076": BalanceLigneMapping(compte_syscohada="7076", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7077": BalanceLigneMapping(compte_syscohada="7077", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7078": BalanceLigneMapping(compte_syscohada="7078", dsf_sheet="BILAN PAYSAGE", dsf_cell="RD", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: RE
    "711": BalanceLigneMapping(compte_syscohada="711", dsf_sheet="BILAN PAYSAGE", dsf_cell="RE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "712": BalanceLigneMapping(compte_syscohada="712", dsf_sheet="BILAN PAYSAGE", dsf_cell="RE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "713": BalanceLigneMapping(compte_syscohada="713", dsf_sheet="BILAN PAYSAGE", dsf_cell="RE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "718": BalanceLigneMapping(compte_syscohada="718", dsf_sheet="BILAN PAYSAGE", dsf_cell="RE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7181": BalanceLigneMapping(compte_syscohada="7181", dsf_sheet="BILAN PAYSAGE", dsf_cell="RE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7182": BalanceLigneMapping(compte_syscohada="7182", dsf_sheet="BILAN PAYSAGE", dsf_cell="RE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7183": BalanceLigneMapping(compte_syscohada="7183", dsf_sheet="BILAN PAYSAGE", dsf_cell="RE", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: RF
    "721": BalanceLigneMapping(compte_syscohada="721", dsf_sheet="BILAN PAYSAGE", dsf_cell="RF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "722": BalanceLigneMapping(compte_syscohada="722", dsf_sheet="BILAN PAYSAGE", dsf_cell="RF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "726": BalanceLigneMapping(compte_syscohada="726", dsf_sheet="BILAN PAYSAGE", dsf_cell="RF", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

    # DSF Reference: RG
    "734": BalanceLigneMapping(compte_syscohada="734", dsf_sheet="BILAN PAYSAGE", dsf_cell="RG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7341": BalanceLigneMapping(compte_syscohada="7341", dsf_sheet="BILAN PAYSAGE", dsf_cell="RG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7342": BalanceLigneMapping(compte_syscohada="7342", dsf_sheet="BILAN PAYSAGE", dsf_cell="RG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "735": BalanceLigneMapping(compte_syscohada="735", dsf_sheet="BILAN PAYSAGE", dsf_cell="RG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7351": BalanceLigneMapping(compte_syscohada="7351", dsf_sheet="BILAN PAYSAGE", dsf_cell="RG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7352": BalanceLigneMapping(compte_syscohada="7352", dsf_sheet="BILAN PAYSAGE", dsf_cell="RG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "736": BalanceLigneMapping(compte_syscohada="736", dsf_sheet="BILAN PAYSAGE", dsf_cell="RG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "737": BalanceLigneMapping(compte_syscohada="737", dsf_sheet="BILAN PAYSAGE", dsf_cell="RG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7371": BalanceLigneMapping(compte_syscohada="7371", dsf_sheet="BILAN PAYSAGE", dsf_cell="RG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),
    "7372": BalanceLigneMapping(compte_syscohada="7372", dsf_sheet="BILAN PAYSAGE", dsf_cell="RG", dsf_field="NET", is_debit=True, multiply_by=1.0, condition=None),

}